book/urls.py
from django.urls import re_path
from . import views

#url for app
urlpatterns = [
    re_path(r'^$', views.form, name='form'),
    re_path(r'^show/$', views.show, name='show'),
    re_path(r'^delete-activity/(?P<pk>\d+)/$', views.delete_activity, name='delete_activity'),
]

homepage/urls.py
from django.urls import path, include
from . import views
from django.conf.urls import url, include
from listresto import urls

app_name = 'homepage'

urlpatterns = [
    path('', views.home, name = "home"),
]

info/urls.py
from django.urls import path, include
from . import views
from django.conf.urls import url, include

app_name = 'info'

urlpatterns = [
    path('', views.info, name = "info"),
]

listresto/urls.py
from django.urls import path, include
from . import views
from django.conf.urls import url, include

app_name = 'listresto'

urlpatterns = [
    path('', views.listresto, name = "listresto"),
]

ppw/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('listresto/', include('listresto.urls')),
    path('info/', include('info.urls')),
    path('book/', include('book.urls')),
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

book/models.py
from django.db import models

# Create your models here.
class ActivityModel(models.Model):
    date = models.DateField()
    hour = models.TimeField(auto_now_add=False)
    name = models.CharField(max_length=100)

homepage/models.py
from django.db import models
from django.utils import timezone

# from django.forms import ModelForm

# Create your models here.
   
class Rest(models.Model):
    
    place   = models.CharField(max_length= 30 ,default="jabodetabek")

    def __str__(self):
        return self.place

class Restaurant(models.Model):
    places  = models.ForeignKey(Rest, on_delete=models.CASCADE)
    nama    = models.CharField(max_length = 30 , default="Random")
    alamat = models.CharField(max_length = 50, default = 'Jl. Depok Kota Depok')
    email = models.EmailField(max_length = 30, default = 'gg@gmail.com')
    desc = models.TextField(default = '')


    likes = 0
    image = models.FileField(upload_to = 'media/', null=True, verbose_name="")

    def __str__(self):
        return self.nama

info/models.py
from django.db import models
from homepage.models import Restaurant

# Create your models here.
class Review(models.Model):
    resto = models.ForeignKey(Restaurant, on_delete = models.CASCADE)
    
    name = models.CharField(max_length = 25, default = '')
    content = models.TextField(default = '')

    def __str__(self):
        return self.name

listresto/models.py
from django.db import models

# Create your models here.

book/forms.py
from django.db import models
from django import forms
from .models import ActivityModel


import datetime

class ActivityForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(
        attrs = {
            "placeholder": 'Name'
        }
    ))
    date = forms.DateField(input_formats=['%Y-%m-%d'], widget=forms.TextInput(
        attrs = {
            "placeholder": 'YYYY-MM-DD'
        }
    ))
    hour = forms.TimeField(input_formats=['%H:%M'], widget=forms.TimeInput(
        attrs = {
            "placeholder": 'Hour:Minute'
        }
    ))


    class Meta:
        model = ActivityModel
        fields = ("name", "date", "hour")
        labels ={
            "name": "Name",
            "date": "Date",
            "hour": "time"
        }

homepage/forms.py
from django import forms
from .models import Rest, Restaurant
from django.forms import ModelForm
from homepage import models

class RestForm(forms.Form):

    place   = forms.CharField(
            label       = 'tempat',
            max_length  = 50,
            required    = True,
            widget      = forms.TextInput(attrs = {'class' : 'form-control form-control-sm', 'placeholder':'gabut'})    
        )

class RestaurantForm(forms.Form):

    nama    = forms.CharField(
            label       = 'tempat',
            max_length  = 50,
            required    = True,
            widget      = forms.TextInput(attrs = {'class' : 'form-control form-control-sm', 'placeholder':'gabut'})    
        )

info/forms.py
from django import forms
from .models import Review
from django.forms import ModelForm, Textarea
# import datetime

class ReviewForm(ModelForm):
    class Meta:
        model = Review

        fields = ["name", 'content']

        widgets = {
            'content': Textarea(attrs={'cols': 80, 'rows': 5}),
        }

book/views.py
from django.shortcuts import render

from django.shortcuts import render
from .models import ActivityModel
from .forms import ActivityForm
from django.shortcuts import get_object_or_404, redirect
from django.contrib import messages


# Create your views here.

def show(request):
    data = ActivityModel.objects.all()
    return render(request, 'form_result.html', {'data':data})

def form(request):
    if request.method == "POST":
        data = ActivityForm(request.POST)
        if data.is_valid():
            data.save()
        else:
            messages.warning(request, 'Data input is not valid, Please try again!')

    return render(request, 'form.html', {'form': ActivityForm()})

def delete_activity(request, pk):
    activity = get_object_or_404(ActivityModel, pk=pk)
    activity.delete()

    form = ActivityForm(instance=activity)

    context = {
        'form' : form,
    }
    return render (request, 'form.html', context)

homepage/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect

from .models import Rest
from .forms import RestForm

# Create your views here.
def home(request):
    html    = "homepage.html"
    if request.method == 'GET':
            form = RestForm()
    elif request.method == 'POST':
            form = RestForm(request.POST)
            #print(request.POST)
            if form.is_valid():
                new_rest = Rest(
                    place= form.data['place']
                )

                new_rest.save()
                print(Rest.objects.all())
                form = RestForm()

                return redirect('rest')
            print(form.errors)
            
    rest    = Rest.objects.all()
    context = {
            'form': form,
            'Rest': rest,
    }
    return render(request, html, context)

info/views.py
from django.shortcuts import render, redirect
from .forms import ReviewForm
from .models import Review
from homepage.models import Restaurant
from django.http import HttpResponse, HttpResponseRedirect

# Create your views here.

def info(request):
    if request.method == 'GET':
        form = ReviewForm()
    elif request.method == 'POST':
        form = ReviewForm(request.POST)
        # print(request.POST)

        if form.is_valid():
            new_review = Review(
                resto = Restaurant.objects.get(pk = 1),
                name = form.data['name'],
                content = form.data['content'],
            )

            new_review.save()
            form = ReviewForm()

        return HttpResponseRedirect('/info/')
    
    reviews = Review.objects.all()

    resto = Restaurant.objects.get(pk = 1)

    imagefile = resto.image

    context = {
        'form': form,
        'reviews': reviews,
        'imagefile': imagefile,
        'resto': resto,
    }

    return render(request, 'info.html', context)

listresto/views.py
from django.shortcuts import render

# Create your views here.
def listresto(request):
    return render(request, 'listresto.html')

book/templates/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Restaurant Reservation</title>
</head>
<body>
    <header style="padding: 100px; background-color: yellow;">
        <h1 style="text-align: center; font-family: Chewy, cursive;"><b>Restaurant Reservation Form</b></h1>
    </header>
        <nav id= "#nav_bar" class="navbar navbar-expand-lg navbar-light navbar-static-top">
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="ml-auto navbar-nav">
                        
                        <li class="nav-item"><a class="nav-link" href="{% url 'info:info' %}"><b>Back</b></a></li>
                        
                        <li class="nav-item"><a class="nav-link" href="{% url 'show' %}"><b>Show Reservation</b></a></li>
                        
                        
                    </ul>
                </div>
            </nav>        
        
    <div style="text-align: center; padding: 50px;">
        {% with url_name=request.resolver_match.url_name %}
        {% if url_name == 'form' %}
        {% else %}
            <h1>Are you sure you want to delete this reservation?</h1>
        {% endif %}
        {% endwith %}
    
        <form action="{% url 'form' %}" method="POST">
            {% csrf_token %}
            <table style="width: 100%; margin-top: 35px; margin-bottom: 35px; padding : 50px; text-align: center;">
                <tr>
                    {{ form.as_table }}
                </tr>
            </table>
            {% with url_name=request.resolver_match.url_name %}
            {% if url_name == 'delete_activity' %}
                <a href="{% url 'show' %}"><button class="btn btn-danger" type="submit">Delete</button></a>
            {% else %}
                <button class="btn-success" type="submit">Reserve</button>
            {% endif %}
        </form>
            {% if messages %}
                <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
                </ul>
            {% endif %}
            {% endwith %}
    </div>
    
</body>
</html>

book/templates/form_result.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Reservation Schedulet</title>
</head>
<body>
  <header style="padding: 100px; background-color: yellow;">
  <h3 style="text-align: center; font-family: Chewy, cursive;"><b>Restaurant Reservation Schedule</b></h3>
  </header>
  <nav id= "#nav_bar" class="navbar navbar-expand-lg navbar-light navbar-static-top">
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="ml-auto navbar-nav">
                        
                        <li class="nav-item"><a class="nav-link" href="{% url 'form' %}"><b>Back</b></a></li>
                        
                    </ul>
                </div>
            </nav>    
  <div style="padding: 50px;">
    <table style="width: 100%; margin-top: 35px; margin-bottom: 35px; padding : 50px; text-align: center;">
            <tr style="text-align: center; font-family: Chewy, cursive;">
              <th>Name</th>
              <th>Date</th>
              <th>Time</th>
              <th></th>
            </tr>
            <tr>
            {% for i in data %}
            <tr style="text-align: center;">
                <td>{{i.name}}</td>
                <td>{{i.date}}</td>
                <td>{{i.hour}}</td>
                <td><a href="{% url 'delete_activity' pk=i.pk %}"> <button class="btn btn-danger"> Delete</button></a></td>
            </tr>
            {% endfor %}
          </table>
</div>

</body>
</html>

homepage/templates/base.html
<!DOCTYPE html>

{% load static %}
<html>

<head class="heading" >
	{% block head %}{%endblock%}
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	
	<title>PewLicious</title>
</head>

<body>
{%block main%}{%endblock%}
</body>
{%block extra%}{%endblock%}
</html>

homepage/templates/home.html
{% extends "base.html" %}

{% load static %}

<html lang="en">
<head>
	{% block head %}
	<link rel="stylesheet" type="text/css" href="{% static '/css/home.css' %}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
	{% endblock %}
</head>
<body>
	{% block main %}
    <h1>Hello World</h1>
    <img src="{% static 'images/healthyfoodbg.png' %}" style="width: 500px;">
    <h1>
        <a href="{% url 'listresto:listresto' %}">BUAT KE PAGE SELANJUTNYA</a>
    </h1>
	{% endblock %}
</body>
</html>

homepage/templates/homepage.html
<!DOCTYPE html>

{% extends "homepagebase.html" %}
{% load static %}

<!--Disclaimer	: there's no bug in this code, there's only feature 
	@author		: Harnindyto wicaksana, 
	contact		: todi.to;-->

<html>
	{% block head %}
		<link rel="stylesheet" type="text/css" href="{% static '/css/home.css' %}">
	{% endblock %}
	{% block main %}
		<div class="bg">
			<div class="makeitmiddle">
				<div class="inthemiddle d-flex justify-content-center">
					<img src="{% static 'images/PewLicious.png' %}" alt="PewLicious logo" align="middle" style="max-width:100%;">
				</div>
				<div class="inthemiddle">
					<form>
						<div class="form-group">
							<select class="form-control" id="exampleFormControlSelect1">
							
							  <option value="" selected disabled hidden>Choose city</option>	
							  {% for j in Rest %}
							  
							  <option>{{ j.place }}</option>
							  
							  {% endfor %}
							</select>
						</div>
					</form>
					<div class="text-right mb-3">
						
						<button type="button" onclick="window.location.href={% url 'listresto:listresto' %}" class="btn btn-outline-danger" style="padding : 0 auto;">Hungry</button>
					</div>
				</div>
			</div>
		</div>
	{% endblock %}
	
</html>

homepage/templates/homepagebase.html
<!DOCTYPE html>

{% load static %}
<html>
<head class="heading" >
	{% block head %}{%endblock%}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

	<title>Pewlicious</title>
	
	<style type="text/css">
		{% block style %}
		{% endblock %}
	</style>
</head>

<body>
{%block main%}{%endblock%}
</body>
{%block extra%}{%endblock%}
</html>

info/templates/info.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="{% static '/css/info.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/css?family=Chewy&display=swap" rel="stylesheet">
    
    <script src="https://kit.fontawesome.com/26197ec3bf.js"></script>

    <title>Info Restoran</title>
</head>

<body>
        <div id="header">
            <div class="container">
                <div class="container-btn">
                    <div class="ml-auto">
                        <button type="button" class="btn btn-danger"><a href="/listresto/?arg={{resto.places.id}}">Back</a></button>
                    </div>
                </div>

                <h1>{{ resto.nama }}</h1>

                <div class="big-container">
                    <div class="container-restoran">
                        <div class="img-container">
                            <img src="{{ resto.image.url }}" alt="RESTORAN-DEPOK-01">
                        </div>
                        <a href="/book/?arg={{resto.id}}" class="btn btn-light">BOOK</a>
                    </div>

                    <div class="container-info">
                        <h4>Alamat: {{ resto.alamat }}</h4>
                        <h4>Email: {{ resto.email }}</h4>
                        <p>{{ resto.desc }}</p>
                        <div class="likes"><button><i class="far fa-thumbs-up"></i></button> 300 Likes</div>
                    </div>
                </div>
            </div>
        </div>

    <div id="review">
        <div class="form-container">
            <h2>Berikan Review</h2>
            <form id="form" action="/info/" method="POST">
                {% csrf_token %}
                {{ form }}
                <button type="submit">SUBMIT</button>
            </form>
        </div>

        <div class="reviews">
            <h4>Review</h4>
            {% for review in reviews %}
                <div class="review">
                    <h5> {{ review.name }} </h5>
                    <p> {{ review.content }} </p>
                </div>
            {% endfor %}
        </div>
    </div>
</body>

<script>'undefined'=== typeof _trfq || (window._trfq = []);'undefined'=== typeof _trfd && (window._trfd=[]),_trfd.push({'tccl.baseHost':'secureserver.net'}),_trfd.push({'ap':'cpsh'},{'server':'p3plcpnl0769'}) // Monitoring performance to make your website faster. If you want to opt-out, please contact web hosting support.</script>

<script src='https://img1.wsimg.com/tcc/tcc_l.combined.1.0.6.min.js'></script><script>'undefined'=== typeof _trfq || (window._trfq = []);'undefined'=== typeof _trfd && (window._trfd=[]),_trfd.push({'tccl.baseHost':'secureserver.net'}),_trfd.push({'ap':'cpsh'},{'server':'p3plcpnl0769'}) // Monitoring performance to make your website faster. If you want to opt-out, please contact web hosting support.</script>

<script src='https://img1.wsimg.com/tcc/tcc_l.combined.1.0.6.min.js'></script>

</html>

listresto/templates/listresto.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static '/css/resto.css' %}">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>List Restoran</title>
</head>
<body>
    <div id = "header">
        <div class = "container">
            <div class="top">
                <h1>Restoran favorit di sekitarmu:</h1>
                <div class="ml-auto">
                    <div class="form-conta">
                        <form class="" action="">
                            <input type="text" placeholder="Search" name="search">
                            <button type="submit"><i class="fa fa-search"></i></button>
                        </form>
                    </div>
                </div>
                <div class="btn-back-2"></div>	
                    <div class="container-btn">
                        <button type="button" class="btn btn-danger" onclick="window.location.href={% url 'homepage:home' %}">Back</button>
                    </div>
                </div>
            </div>
        </div>
		
		<div class = "resto clearfix">
			<div class = "img-resto left-section">
				<img src="{% static '/images/resto-depok-01.jpeg' %}" style="width: 300px; height: 200px;" alt="RESTORAN-DEPOK-01">
			</div>
			<div style="padding-top: 20px;">
				<h2>[NAMA RESTORAN]</h2>
				<div class = "content-resto">
					<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores, placeat nesciunt tempora deleniti voluptas quisquam aut, ut rerum dignissimos ab excepturi dolores necessitatibus beatae cum neque. Omnis sed dolorem, eaque soluta rem corrupti, necessitatibus ab quisquam fugiat ullam voluptate, facilis tempora et cumque quod assumenda dignissimos. Numquam quae pariatur nihil obcaecati vel! Id quasi iste doloribus debitis tempora iusto a, aliquid deleniti provident nobis, doloremque explicabo magni tempore odit eligendi sed! Suscipit quae laudantium totam.</p>
				</div>
				<div class="container-btn">
					<div class="ml-auto">
						<button type="button" class="btn btn-warning" onclick="window.location.href={% url 'info:info' %}">Lihat</button>
					</div>
				</div>
			</div>
		</div>
	</body>
    <h1>
        <a href="{% url 'info:info' %}">BUAT KE PAGE SELANJUTNYA</a>
    </h1>
    <h1>
        <a href="{% url 'homepage:home' %}">BUAT KE PAGE SEBELUMNYA</a>
    </h1>
</body>
</html>